[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[fmt]
line_length = 80
tab_width = 4
bracket_spacing = false
int_types = "preserve"
quote_stile = "double"
[rpc_endpoints]
sepolia = "${RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
